services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_med
      - POSTGRES_PASSWORD=db_med
      - POSTGRES_DB=db_med